### ISSUE TITLE
specifying verbose flag to osqueryd/osqueryi causes extension to not load

### ISSUE THREAD

**Issue by AndrewTucker2017** [aquasecurity/kube-query#14]
When using osquery 4.3.0 and autoloading kube-query as an extension, passing the --verbose flag to osqueryd/osqueryi causes the extension to not load due to an unrecognized CLI parameter.

When the verbose parameter is removed, everything works fine.

Seems like a simple change to recognize the verbose parameter and not fail when it is passed on by osquery running in verbose mode.

See below for a shell session that demonstrates the error:

bash-4.2#   osqueryi --nodisable_extensions --verbose
I0618 18:34:15.327247 17507 init.cpp:343] osquery initialized [version=4.3.0]
I0618 18:34:15.327378 17507 extensions.cpp:434] Found autoloadable extension: /etc/osquery/kube-query.ext
I0618 18:34:15.327440 17507 dispatcher.cpp:77] Adding new service: WatcherRunner (0x3d040e8) to thread: 140596147271424 (0x3c10b10) in process 17507
I0618 18:34:15.327589 17507 dispatcher.cpp:77] Adding new service: ExtensionWatcher (0x3c12e18) to thread: 140596138878720 (0x3c16ee0) in process 17507
I0618 18:34:15.327643 17507 dispatcher.cpp:77] Adding new service: ExtensionRunnerCore (0x3c18bd8) to thread: 140596130486016 (0x3c16b10) in process 17507
I0618 18:34:15.327857 17508 watcher.cpp:629] Created and monitoring extension child (17511): /etc/osquery/kube-query.ext
I0618 18:34:15.327924 17507 auto_constructed_tables.cpp:96] Removing stale ATC entries
I0618 18:34:15.328143 17510 interface.cpp:268] Extension manager service starting: /root/.osquery/shell.em
I0618 18:34:15.328402 17507 options.cpp:100] Verbose logging enabled by config option
I0618 18:34:15.328431 17507 options.cpp:100] Verbose logging enabled by config option
flag provided but not defined: -verbose
Usage of /etc/osquery/kube-query.ext:
  -interval string
    	flag for specifying wait time before registering on autoload
  -kubeconfig string
    	absolute path to the kubeconfig file (can be set by KUBECONFIG environment variable)
  -socket string
    	absolute path to the osquery socket
  -timeout string
    	flag for specifying wait time before registering on autoload
I0618 18:34:15.356397 17507 smbios_tables.cpp:104] Reading SMBIOS from sysfs DMI node
I0618 18:34:15.356528 17507 events.cpp:1122] Error registering subscriber: process_file_events: Subscriber disabled via configuration
Using a virtual database. Need help, type '.help'
osquery>

**Comment by danielsagi** [comment]
Thanks @AndrewTucker2017 !
We really appreciate your detailed issue, and just created a new PR to fix this bug. #15
